# Generated by Django 4.0.6 on 2022-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('stuck', 'stuck'), ('failed', 'failed'), ('finished', 'finished')], max_length=128)),
                ('failReason', models.TextField(max_length=10000)),
                ('yaml', models.JSONField()),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
