# Generated by Django 4.0.6 on 2022-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='yaml',
            field=models.CharField(max_length=50000),
        ),
    ]
