# Generated by Django 4.0.6 on 2022-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jobs_yaml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='failReason',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('stuck', 'stuck'), ('failed', 'failed'), ('finished', 'finished')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='uuid',
            field=models.UUIDField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='yaml',
            field=models.TextField(max_length=50000),
        ),
    ]
